package:
  name: optiktools
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../
  git_url: https://github.com/MartinPdeS/OptikTools.git

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

channels:
  - conda-forge
  - martinpdes

requirements:
  host:
    - python {{ PY_VER }}*
    - setuptools >=40.8.0
    - wheel
    - setuptools-scm >=8.0
    - pip
  run:
    - martinpdes::mpsplots
    - martinpdes::typedunit
    - numpy

about:
  home: https://github.com/MartinPdeS/OptikTools
  license: MIT
  summary: "A package for Gaussian optics."
  description: OptikTools is a library that helps the end-user to build it's own Gaussian optics library.
  dev_url: https://github.com/MartinPdeS/OptikTools
  doc_url: https://martinpdes.github.io/OptikTools/
  license_file: LICENSE
  keywords:
    - optics
    - refractive index
    - material

test:
  imports:
    - OptikTools
  requires:
    - python {{ PY_VER }}*
    - pytest>=0.6
    - pytest-cov>=2.0
    - pytest-json-report==1.5.0
    - coverage==7.6.1
  commands:
    - python -m pytest
  source_files:
    - tests/*

extra:
  recipe-maintainers:
    - MartinPdeS